name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # SSH Key für Login auf den Server hinzufügen
    - name: Add SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/github-deploy-directus
        chmod 600 ~/.ssh/github-deploy-directus
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
      shell: bash

    # Push dein komplettes Repository auf den Server
    - name: Deploy Project to Server
      run: |
        rsync -avz -e "ssh -i ~/.ssh/github-deploy-directus -o StrictHostKeyChecking=no" ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/www/vhosts/himmelsteil.com/directus.himmelsteil.com/

    # Docker Compose auf dem Server ausführen
    - name: Execute Docker Compose
      run: |
        ssh -i ~/.ssh/github-deploy-directus -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          cd /var/www/vhosts/himmelsteil.com/directus.himmelsteil.com/
          docker compose up -d --force-recreate
        EOF
